image: node:18.12.1

pipelines:
  branches:
    default:
      - step:
          script:
            - npm install
    master:
      - step:
          caches:
            - node
          script:
            - export BB_TOKEN=$BB_TOKEN
            - export HUSKY=0
            - npm install
            - npm run build
            - npx semantic-release -b master
